CC=g++
compile:
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Reliability.o" "src/Reliability.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/KeyTreeLocalSearch.o" "src/KeyTreeLocalSearch.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Greedy.o" "src/Greedy.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Graph.o" "src/Graph.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Edge.o" "src/Edge.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/ResultRVR.o" "src/ResultRVR.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/main.o" "src/main.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Node.o" "src/Node.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/RVR.o" "src/RVR.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Utilities.o" "src/Utilities.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/ComponentDinArray.o" "src/ComponentDinArray.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Pair.o" "src/Pair.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/ExtendedCut.o" "src/ExtendedCut.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Collection.o" "src/Collection.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/KeyTree.o" "src/KeyTree.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Object.o" "src/Object.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Integer.o" "src/Integer.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Algorithms.o" "src/Algorithms.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Component.o" "src/Component.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/DirectedGraph.o" "src/DirectedGraph.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/VNS.o" "src/VNS.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Boolean.o" "src/Boolean.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Construction.o" "src/Construction.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/NetworkDesign.o" "src/NetworkDesign.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Number.o" "src/Number.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/EmptyHeapException.o" "src/EmptyHeapException.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Test.o" "src/Test.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/BinaryHeap.o" "src/BinaryHeap.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/SwapKeyPathLocalSearch.o" "src/SwapKeyPathLocalSearch.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Path.o" "src/Path.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/FullHeapException.o" "src/FullHeapException.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/SwapNodeLocalSearch.o" "src/SwapNodeLocalSearch.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/Adyacence.o" "src/Adyacence.cpp" 
	$(CC) -O0 -g3 -Wall -c -fmessage-length=0 -o "obj/KeyPathLocalSearch.o" "src/KeyPathLocalSearch.cpp"

dist:
	$(CC) -o NetworkDesign "obj/main.o" "obj/VNS.o" "obj/Utilities.o" "obj/Test.o" "obj/SwapNodeLocalSearch.o" "obj/SwapKeyPathLocalSearch.o" "obj/ResultRVR.o" "obj/Reliability.o" "obj/RVR.o" "obj/Path.o" "obj/Pair.o" "obj/Object.o" "obj/Number.o" "obj/Node.o" "obj/NetworkDesign.o" "obj/KeyTreeLocalSearch.o" "obj/KeyTree.o" "obj/KeyPathLocalSearch.o" "obj/Integer.o" "obj/Greedy.o" "obj/Graph.o" "obj/FullHeapException.o" "obj/ExtendedCut.o" "obj/EmptyHeapException.o" "obj/Edge.o" "obj/DirectedGraph.o" "obj/Construction.o" "obj/ComponentDinArray.o" "obj/Component.o" "obj/Collection.o" "obj/Boolean.o" "obj/BinaryHeap.o" "obj/Algorithms.o" "obj/Adyacence.o"